# Site settings
title: 
header-img: img/home-bg.png
email: guy.s.bryant@gmail.com
copyright_name: guysbryant
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  guysbryant
learn_profile: guysbryant
email_username: guy.s.bryant@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
